### ISSUE TITLE
Is it possible to use listUpcomingEvents function from a different page/component

### ISSUE THREAD

**Issue by marcoseoane** [Insomniiak/react-google-calendar-api#18]
When I call listUpcomingEvents from the same component in my app that I actioned the handleAuthClick method it works, but when I attempt to call this function from another page it tells me 'this.gapi is not loaded" & that the listUpcomingEvents is not a function?

Is there a way to authenticate from one component/page in my app and call listUpcomingEvents from a different one?

Just to provide some context I am working with create-react-app using react-router 4

Thank you very much,
Marco

**Comment by Insomniiak** [comment]
Normally, yes
Will check this in few minutes,
Your component(react-google-calendar-api) need to be instanced at the start of your app and never be destroy

Aymeric

**Comment by marcoseoane** [comment]
> Normally, yes
> Will check this in few minutes,
> Your component(react-google-calendar-api) need to be instanced at the start of your app and never be destroy
> 
> Aymeric

Thanks, if there is anything else I can provide to help please let me know

**Comment by Insomniiak** [comment]
Do you create the ApiCalendar component on your main Page/Application?

**Comment by marcoseoane** [comment]
> Do you create the ApiCalendar component on your main Page/Application?

Not sure if i'm 'creating' it on my main page maybe thats a step i'm missing, but what I'm doing currently is importing the package in my index.js file which handles all of the react-router stuff and pass the ApiCalendar down as a prop to the two pages/components that I want to authenticate from & call the listUpcomingEvents function from.

**Comment by Insomniiak** [comment]
Ok seems good so,
Can you show me the code for the router?

**Comment by marcoseoane** [comment]
import React from "react";
import ReactDOM from "react-dom";
import { unregister } from "./registerServiceWorker";
import { Provider } from "react-redux";
import { ConnectedRouter } from "react-router-redux";
import { Route, Switch } from "react-router";

import { createStore, applyMiddleware } from "redux";
import { createBrowserHistory } from "history";
import { routerMiddleware } from "react-router-redux";
import { composeWithDevTools } from "redux-devtools-extension";
import { persistStore, autoRehydrate, getStoredState } from "redux-persist";
import thunk from "redux-thunk";
import rootReducer from "./reducers/index";

import About from "./containers/About";
import Professionals from "./containers/Professionals";
import Employers from "./containers/Employers";
import Agencies from "./containers/Agencies";
import AgenciesList from "./containers/company/agency/AgenciesList";
import AgenciesSuggestions from "./containers/AgenciesSuggestions";
import CompanyNew from "./containers/company/CompanyNew";
import CompanyEdit from "./containers/company/CompanyEdit";
import CompanyProfile from "./containers/company/CompanyProfile";
import Cookies from "./containers/Cookies";
import EmployersList from "./containers/company/employer/EmployersList";
import EmployersSuggestions from "./containers/EmployersSuggestions";
import Home from "./containers/Home";
import Jobs from "./containers/Jobs";
import JobDetailContainer from "./containers/JobDetailContainer";
import MyJobs from "./containers/MyJobs";
import Pricing from "./containers/Pricing";
import JobApplications from "./containers/JobApplications";
import Messages from "./containers/Messages";
import Search from "./containers/Search";
import ForgotPassword from "./containers/OuterPages/ForgotPassword";
import ResetPassword from "./containers/OuterPages/ResetPassword";

import ProfessionalSignup from "./containers/OuterPages/ProfessionalSignup/index.js";
import ProfessionalSignin from "./containers/OuterPages/ProfessionalSignin";
import ProfessionalLogoff from "./containers/OuterPages/ProfessionalLogoff";
import ProfessionalOnboard from "./containers/ProfessionalOnboard";
import ProfessionalSkillsRating from "./containers/ProfessionalSkillsRating";
import ProfessionalDashboard from "./containers/ProfessionalDashboard";
import CompanySignup from "./containers/CompanySignup";
import ProfessionalProfile from "./containers/professional/ProfessionalProfile";
import ProfessionalProfileSettings from "./containers/ProfessionalProfileSettings";
import ProfessionalsList from "./containers/professional/ProfessionalsList";
import NotificationList from "./containers/notification/NotificationList";
import ProfessionalsSuggestions from "./containers/ProfessionalsSuggestions";
import ActivityShow from "./containers/activity/ActivityShow";
import Settings from "./containers/Settings";
import Privacy from "./containers/Privacy";
import Terms from "./containers/Terms";
import HoverTest from "./containers/HoverTest";
import UserNotFound from "./containers/UserNotFound";
import RequestService from "./services/RequestService";
import InviteFriends from "./containers/InviteFriends";
import Components from "./containers/Components";

import "./assets/stylesheets/css/styles.css";
import "react-select/dist/react-select.css";
import "../node_modules/video-react/dist/video-react.css";

import ReactGA from "react-ga";

const history = createBrowserHistory();

const trackPageView = location => {
  ReactGA.set({ page: location.pathname });
  ReactGA.pageview(location.pathname);
};

const initGa = history => {
  ReactGA.initialize(process.env.REACT_APP_ANALYTICS, {
    debug: false
  });
  trackPageView(history.location);
  history.listen(trackPageView);
};

initGa(history);

getStoredState(
  {
    whitelist: ["session"]
  },
  (err, loadedState) => {
    const middleware = [thunk, routerMiddleware(history)];
    const store = createStore(
      rootReducer,
      loadedState,
      composeWithDevTools(applyMiddleware(...middleware), autoRehydrate())
    );

    persistStore(store, {
      whitelist: ["session", "chosenSkill", "chosenCategory", "onboardskill"]
    });

    RequestService.getSession = function() {
      return store.getState().session || {};
    };

    ReactDOM.render(
      <Provider store={store}>
        <ConnectedRouter history={history}>
          <div>
            <Route exact path="/" component={About} />
            <Route path="/:uniqueWordPath">
              <div>
                <Switch>
                  <Route exact path="/components" component={Components} />
                  <Route exact path="/about" component={About} />
                  <Route
                    exact
                    path="/professionals"
                    component={Professionals}
                  />
                  <Route exact path="/employers" component={Employers} />
                  <Route exact path="/agencies" component={Agencies} />
                  <Route exact path="/cookies" component={Cookies} />
                  <Route exact path="/hovertest" component={HoverTest} />
                  <Route exact path="/signup" component={ProfessionalSignup} />
                  <Route exact path="/signin" component={ProfessionalSignin} />
                  <Route exact path="/logoff" component={ProfessionalLogoff} />
                  <Route
                    exact
                    path="/forgotpassword"
                    component={ForgotPassword}
                  />
                  <Route
                    exact
                    path="/resetpassword"
                    component={ResetPassword}
                  />
                  <Route exact path="/search/:query" component={Search} />
                  <Route exact path="/search" component={Search} />
                  <Route
                    exact
                    path="/onboard"
                    component={ProfessionalOnboard}
                  />
                  <Route
                    exact
                    path="/skills"
                    component={ProfessionalSkillsRating}
                  />
                  <Route
                    exact
                    path="/agency/suggestions/:followerId?/:followerType?"
                    component={AgenciesSuggestions}
                  />
                  <Route
                    exact
                    path="/employer/suggestions/:followerId?/:followerType?"
                    component={EmployersSuggestions}
                  />
                  <Route
                    exact
                    path="/professional/suggestions/:followerId?/:followerType?"
                    component={ProfessionalsSuggestions}
                  />
                  <Route
                    exact
                    path="/company/:type/new"
                    component={CompanyNew}
                  />
                  <Route
                    path="/company/:mentionTag/edit"
                    component={CompanyEdit}
                  />
                  <Route
                    path="/company/:mentionTag"
                    component={CompanyProfile}
                  />
                  <Route
                    exact
                    path="/dashboard"
                    component={ProfessionalDashboard}
                  />
                  <Route
                    exact
                    path="/profile/edit"
                    component={ProfessionalProfileSettings}
                  />
                  <Route exact path="/agencies" component={AgenciesList} />
                  <Route exact path="/employers" component={EmployersList} />
                  <Route
                    exact
                    path="/professionals"
                    component={ProfessionalsList}
                  />
                  <Route
                    exact
                    path="/notifications"
                    component={NotificationList}
                  />
                  <Route exact path="/settings" component={Settings} />
                  <Route exact path="/home" component={Home} />
                  <Route
                    exact
                    path="/companysignup"
                    component={CompanySignup}
                  />
                  <Route
                    exact
                    path="/jobs/applications"
                    component={JobApplications}
                  />
                  <Route
                    exact
                    path="/jobs/:jobId"
                    component={JobDetailContainer}
                  />
                  <Route exact path="/jobs" component={MyJobs} />
                  <Route exact path="/pricing" component={Pricing} />
                  <Route exact path="/messages" component={Messages} />
                  <Route exact path="/privacy" component={Privacy} />
                  <Route exact path="/terms" component={Terms} />
                  <Route
                    exact
                    path="/activities/:id"
                    component={ActivityShow}
                  />
                  <Route exact path="/notfound" component={UserNotFound} />
                  <Route
                    exact
                    path="/invite-friends"
                    component={InviteFriends}
                  />
                  <Route
                    path="/:username"
                    component={args => {
                      return (
                        <ProfessionalProfile
                          username={args.match.params.username}
                        />
                      );
                    }}
                  />
                </Switch>
              </div>
            </Route>
          </div>
        </ConnectedRouter>
      </Provider>,
      document.getElementById("root")
    );

    unregister();
  }
);

**Comment by marcoseoane** [comment]
> Ok seems good so,
> Can you show me the code for the router?

here you go, I left out a long list of imports so thats not clogging up the comment but heres everything from the import of your package downwards

import ApiCalendar from 'react-google-calendar-api'

const history = createBrowserHistory();

const trackPageView = location => {
  ReactGA.set({ page: location.pathname });
  ReactGA.pageview(location.pathname);
};

const initGa = history => {
  ReactGA.initialize(process.env.REACT_APP_ANALYTICS, {
    debug: false
  });
  trackPageView(history.location);
  history.listen(trackPageView);
};

initGa(history);

getStoredState(
  {
    whitelist: ["session"]
  },
  (err, loadedState) => {
    const middleware = [thunk, routerMiddleware(history)];
    const store = createStore(
      rootReducer,
      loadedState,
      composeWithDevTools(applyMiddleware(...middleware), autoRehydrate())
    );

    persistStore(store, {
      whitelist: ["session", "chosenSkill", "chosenCategory", "onboardskill"]
    });

    RequestService.getSession = function() {
      return store.getState().session || {};
    };

    ReactDOM.render(
      <Provider store={store}>
        <ConnectedRouter history={history}>
          <div>
            <Route exact path="/" component={About} />
            <Route path="/:uniqueWordPath">
              <div>
                <Switch>
                  <Route exact path="/components" component={Components} />
                  <Route exact path="/about" component={About} />
                  <Route
                    exact
                    path="/professionals"
                    component={Professionals}
                  />
                  <Route exact path="/employers" component={Employers} />
                  <Route exact path="/agencies" component={Agencies} />
                  <Route exact path="/cookies" component={Cookies} />
                  <Route exact path="/hovertest" component={HoverTest} />
                  <Route exact path="/signup" component={ProfessionalSignup} />
                  <Route exact path="/signin" component={ProfessionalSignin} />
                  <Route exact path="/logoff" component={ProfessionalLogoff} />
                  <Route
                    exact
                    path="/forgotpassword"
                    component={ForgotPassword}
                  />
                  <Route
                    exact
                    path="/resetpassword"
                    component={ResetPassword}
                  />
                  <Route exact path="/search/:query" component={Search} />
                  <Route exact path="/search" component={Search} />
                  <Route
                    exact
                    path="/onboard"
                    component={ProfessionalOnboard}
                  />
                  <Route
                    exact
                    path="/skills"
                    component={ProfessionalSkillsRating}
                  />
                  <Route
                    exact
                    path="/agency/suggestions/:followerId?/:followerType?"
                    component={AgenciesSuggestions}
                  />
                  <Route
                    exact
                    path="/employer/suggestions/:followerId?/:followerType?"
                    component={EmployersSuggestions}
                  />
                  <Route
                    exact
                    path="/professional/suggestions/:followerId?/:followerType?"
                    component={ProfessionalsSuggestions}
                  />
                  <Route
                    exact
                    path="/company/:type/new"
                    component={CompanyNew}
                  />
                  <Route
                    path="/company/:mentionTag/edit"
                    component={CompanyEdit}
                  />
                  <Route
                    path="/company/:mentionTag"
                    component={CompanyProfile}
                  />
                  <Route
                    exact
                    path="/dashboard"
                    component={ProfessionalDashboard}
                  />
                  <Route
                    exact
                    path="/profile/edit"
                    component={ProfessionalProfileSettings}
                  />
                  <Route exact path="/agencies" component={AgenciesList} />
                  <Route exact path="/employers" component={EmployersList} />
                  <Route
                    exact
                    path="/professionals"
                    component={ProfessionalsList}
                  />
                  <Route
                    exact
                    path="/notifications"
                    component={NotificationList}
                  />
                  <Route exact path="/settings" component={()=>{
                    return <Settings ApiCalendar={ApiCalendar}/>
                  }} />
                  <Route exact path="/home" component={Home} />
                  <Route
                    exact
                    path="/companysignup"
                    component={CompanySignup}
                  />
                  <Route
                    exact
                    path="/jobs/applications"
                    component={JobApplications}
                  />
                  <Route
                    exact
                    path="/jobs/:jobId"
                    component={()=>{
                      return <JobDetailContainer ApiCalendar={ApiCalendar}/>
                    }}
                  />
                  <Route exact path="/jobs" component={MyJobs} />
                  <Route exact path="/pricing" component={Pricing} />
                  <Route exact path="/messages" component={Messages} />
                  <Route exact path="/privacy" component={Privacy} />
                  <Route exact path="/terms" component={Terms} />
                  <Route
                    exact
                    path="/activities/:id"
                    component={ActivityShow}
                  />
                  <Route exact path="/notfound" component={UserNotFound} />
                  <Route
                    exact
                    path="/invite-friends"
                    component={InviteFriends}
                  />
                  <Route
                    path="/:username"
                    component={args => {
                      return (
                        <ProfessionalProfile
                          username={args.match.params.username}
                        />
                      );
                    }}
                  />
                </Switch>
              </div>
            </Route>
          </div>
        </ConnectedRouter>
      </Provider>,
      document.getElementById("root")
    );

    unregister();
  }
);

**Comment by Insomniiak** [comment]
Can you print ApiCalendar.gapi in both components?
