### ISSUE TITLE
Authentication Callback

### ISSUE THREAD

**Issue by carlmagumpara** [Insomniiak/react-google-calendar-api#19]
Please add call back for authentication. 

Ex: 
ApiCalendar.handleAuthClick()
.then((result) => {
   console.log(result);
}).catch((error) => {
   console.log(error);
});

**Comment by Insomniiak** [comment]
Hi,
Yeah its possible, just need to find the time, will try today.

But if you want to make a contribution you can, Just transform:
```javascript
```

**Comment by carlmagumpara** [comment]
> Hi,
> Yeah its possible, just need to find the time, will try today.
> 
> But if you want to make a contribution you can, Just transform:
> 
> ```js
>     public handleAuthClick(): void {
>         if (this.gapi) {
>             this.gapi.auth2.getAuthInstance().signIn();
>         } else {
>             console.log("Error: this.gapi not loaded")
>         }
> }
> ```
> 
> Into:
> 
> ```js
>     public handleAuthClick(): void {
>         if (this.gapi) {
>             return this.gapi.auth2.getAuthInstance().signIn();
>         } else {
>             console.log("Error: this.gapi not loaded")
>             return Promise.reject(new Error("Error: this.gapi not loaded"));
>         }
> }
> ```

Hi, can i be a contributor?

**Comment by Insomniiak** [comment]
Yeah, sure, just create a Pull Request, and assign me in Review when its done.

Thanks

**Comment by Insomniiak** [comment]
And replace the return function: `void` by `any` or by the real type

**Comment by Insomniiak** [comment]
@carlmagumpara Any updates?
