### ISSUE TITLE
Fails to minify using create-react-app

### ISSUE THREAD

**Issue by Strat1987** [Insomniiak/react-google-calendar-api#9]
Dear,
While trying to use your API I stumble across following issue when performing yarn build:

Failed to minify the code from this file:

 	./node_modules/react-google-calendar-api/ApiCalendar.js:2

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

Thanks in advance!

**Comment by Insomniiak** [comment]
Hi,
Yeah, I think this is because I published ES6 Code, I will fix this issue soon, when I find the Time to work a little bit on it.
Thanks you for the Feedback

Cordialement
Aymeric Beudaert
________________________________

**Comment by Insomniiak** [comment]
@Strat1987 Is this solved for you?

**Comment by Insomniiak** [comment]
Issue solved normally
